# Generated by Django 4.1.13 on 2024-09-06 11:19

from django.db import migrations, models
import lex.lex_app.rest_api.fields.XLSX_field


class Migration(migrations.Migration):

    dependencies = [
        ('lex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.TextField(null=True)),
                ('logfile', lex.lex_app.rest_api.fields.XLSX_field.XLSXField(default='', max_length=300, upload_to='')),
                ('input_validation', lex.lex_app.rest_api.fields.XLSX_field.XLSXField(default='', max_length=300, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('traceback', models.TextField(default='', null=True)),
                ('calculationId', models.TextField(default='-1')),
                ('calculation_record', models.TextField(default='legacy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('group',), name='defining_fields_Log'),
        ),
    ]
