# Generated by Django 4.2.20 on 2025-04-11 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lex_app", "0002_auditlog_revisions_calculationlog_calculationlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationlog",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 11, 11, 50, 4, 586450)
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculationlog",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 11, 11, 50, 4, 586450)
            ),
        ),
    ]
