# Generated by Django 4.2.20 on 2025-04-16 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_app', '0003_alter_calculationlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 11, 23, 58, 824358)),
        ),
        migrations.AlterField(
            model_name='historicalcalculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 11, 23, 58, 824358)),
        ),
    ]
