# Generated by Django 4.2.20 on 2025-05-07 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_app', '0011_remove_calculationlog_calculation_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 9, 45, 59, 557156)),
        ),
        migrations.AlterField(
            model_name='historicalcalculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 9, 45, 59, 557156)),
        ),
    ]
