# Generated by Django 4.2.20 on 2025-05-07 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_app', '0012_alter_calculationlog_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserchangelog',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='UserChangeLog',
        ),
        migrations.AlterField(
            model_name='calculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 9, 46, 21, 385067)),
        ),
        migrations.AlterField(
            model_name='historicalcalculationlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 9, 46, 21, 385067)),
        ),
        migrations.DeleteModel(
            name='HistoricalUserChangeLog',
        ),
    ]
