# Generated by Django 4.2.20 on 2025-05-09 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lex_app", "0017_alter_calculationlog_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationlog",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 9, 17, 45, 45, 381370)
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculationlog",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 9, 17, 45, 45, 381370)
            ),
        ),
    ]
